"""update to user model fields to comform to python variable naming conversion

Revision ID: 1b29114ed538
Revises: c3fc0fd5e171
Create Date: 2025-05-14 17:03:33.279288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b29114ed538'
down_revision: Union[str, None] = 'c3fc0fd5e171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user_account', 'updatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('user_account', 'updated_at')
    # ### end Alembic commands ###
