"""add sermon model

Revision ID: 3407aba4eb5f
Revises: d159c8854e02
Create Date: 2025-05-21 11:58:10.037912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3407aba4eb5f"
down_revision: Union[str, None] = "d159c8854e02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("podcasts", sa.Column("cover_image", sa.String(), nullable=True))
    op.add_column("podcasts", sa.Column("video_file", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("podcasts", "video_file")
    op.drop_column("podcasts", "cover_image")
    # ### end Alembic commands ###
