"""empty message

Revision ID: 80d9c3cee725
Revises: 8e78af4ea04f
Create Date: 2025-07-04 19:55:55.899268

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80d9c3cee725"
down_revision: Union[str, None] = "8e78af4ea04f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sermons",
        sa.Column(
            "cld_image_public_id", sa.String(), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "sermons",
        sa.Column(
            "cld_audio_public_id", sa.String(), nullable=False, server_default=""
        ),
    )
    op.drop_column("sermons", "img_public_id")
    op.drop_column("sermons", "audio_public_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sermons",
        sa.Column("audio_public_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "sermons",
        sa.Column("img_public_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("sermons", "cld_audio_public_id")
    op.drop_column("sermons", "cld_image_public_id")
    # ### end Alembic commands ###
