"""add public id for cover img and audio and remove generic public id

Revision ID: 8e78af4ea04f
Revises: a5bc5df1b34d
Create Date: 2025-07-04 19:14:35.737454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e78af4ea04f"
down_revision: Union[str, None] = "a5bc5df1b34d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sermons",
        sa.Column("img_public_id", sa.String(), nullable=False, server_default=""),
    )
    op.add_column(
        "sermons",
        sa.Column("audio_public_id", sa.String(), nullable=False, server_default=""),
    )
    op.drop_column("sermons", "cloudinary_public_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sermons",
        sa.Column(
            "cloudinary_public_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("sermons", "audio_public_id")
    op.drop_column("sermons", "img_public_id")
    # ### end Alembic commands ###
