"""empty message

Revision ID: a5bc5df1b34d
Revises: 1bb36057ffb0
Create Date: 2025-07-04 19:00:00.176905

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5bc5df1b34d"
down_revision: Union[str, None] = "1bb36057ffb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sermons",
        sa.Column(
            "cloudinary_public_id", sa.String(), nullable=False, server_default=""
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sermons", "cloudinary_public_id")
    # ### end Alembic commands ###
