"""add fields to podcast to track cloudinary urls

Revision ID: c5a25449df2a
Revises: 80d9c3cee725
Create Date: 2025-07-10 18:33:31.685624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a25449df2a'
down_revision: Union[str, None] = '80d9c3cee725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('cld_image_public_id', sa.String(), nullable=True))
    op.add_column('podcasts', sa.Column('cld_video_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'cld_video_public_id')
    op.drop_column('podcasts', 'cld_image_public_id')
    # ### end Alembic commands ###
